### ISSUE TITLE
Error starting WSServer

### ISSUE THREAD

**Issue by jwulf** [salboaie/SwarmCore#2]
[~/workspace/SwarmCore] $ ls autolib/
SwarmAcl.js
sitapati@MacBook-Air [~/workspace/SwarmCore] $ node etc/adapters/WSServer.js 
Error: ENOENT, no such file or directory '/Users/sitapati/workspace/SwarmESB/autolib/'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at includeRec (/Users/sitapati/workspace/SwarmCore/lib/loadAutoLibs.js:5:19)
    at Object.<anonymous> (/Users/sitapati/workspace/SwarmCore/lib/loadAutoLibs.js:41:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
{ [Error: ENOENT, no such file or directory '/Users/sitapati/workspace/SwarmESB/autolib/']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/sitapati/workspace/SwarmESB/autolib/',
  syscall: 'stat' } 'Error: ENOENT, no such file or directory \'/Users/sitapati/workspace/SwarmESB/autolib/\'\n    at Error (native)\n    at Object.fs.statSync (fs.js:797:18)\n    at includeRec (/Users/sitapati/workspace/SwarmCore/lib/loadAutoLibs.js:5:19)\n    at Object.<anonymous> (/Users/sitapati/workspace/SwarmCore/lib/loadAutoLibs.js:41:1)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)'
Uncaught exception in global handler

**Comment by jwulf** [comment]
found it: wrong SWARM_PATH set in .bash_profile
