### ISSUE TITLE
Adapter continually reloads when launched from Launcher.js

### ISSUE THREAD

**Issue by jwulf** [salboaie/SwarmCore#6]
When launched directly:

```
sitapati@MacBook-Air [~/workspace/SwarmCore] $ node etc/adapters/AtmaMailAdapter.js 
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
info: Mailin Smtp server listening on port 10025
```

When launched from Launcher.js:

```
sitapati@MacBook-Air [~/workspace/SwarmCore] $ node etc/adapters/Launcher.js
...
Missing any node in group [Core]

Dropping swarm CoreWork.js targeted towards dead node or group: null
Error
    at createDebugRecord (/Users/sitapati/workspace/SwarmCore/node_modules/semantic-firewall/lib/standardLogs.js:44:27)
    at LogsCore.sf.logger.addCase.message [as logError] (/Users/sitapati/workspace/SwarmCore/node_modules/semantic-firewall/lib/standardLogs.js:91:26)
    at /Users/sitapati/workspace/SwarmCore/com/redisComImpl.js:493:40
    at callItFinally (/Users/sitapati/workspace/SwarmCore/node_modules/asynchron/lib/asynchron.js:102:26)
    at _endCall (/Users/sitapati/workspace/SwarmCore/node_modules/asynchron/lib/asynchron.js:84:17)
    at /Users/sitapati/workspace/SwarmCore/node_modules/asynchron/lib/asynchron.js:117:25
    at _fulfilled (/Users/sitapati/workspace/SwarmCore/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Users/sitapati/workspace/SwarmCore/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Users/sitapati/workspace/SwarmCore/node_modules/q/q.js:756:13)
    at /Users/sitapati/workspace/SwarmCore/node_modules/q/q.js:516:49
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
info: Mailin Smtp server listening on port 10025
Watching  /Users/sitapati/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
info: Mailin Smtp server listening on port 10025
Watching  /Users/sitapati/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
info: Mailin Smtp server listening on port 10025
```

This repeats every few seconds, non-stop.

**Comment by jwulf** [comment]
Using the config from SwarmESB the exception disappears, but the adapter is still being continually reloaded:
```
Node _WSServer(fbd73221-4806-467d-9e8d-77fd19df352e) ready for swarms!
Watching  /Users/sitapati/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
Registering node  _WSServer(fbd73221-4806-467d-9e8d-77fd19df352e)
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
Booting Mail adapter...
Mon Jun 01 2015 08:52:52 GMT+1000 (AEST)
info: Mailin Smtp server listening on port 10025
Watching  /Users/sitapati/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
Booting Mail adapter...
Mon Jun 01 2015 08:52:54 GMT+1000 (AEST)
info: Mailin Smtp server listening on port 10025
Watching  /Users/sitapati/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
Booting Mail adapter...
Mon Jun 01 2015 08:52:56 GMT+1000 (AEST)
info: Mailin Smtp server listening on port 10025
Watching  /Users/sitapati/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
Booting Mail adapter...
Mon Jun 01 2015 08:52:58 GMT+1000 (AEST)
info: Mailin Smtp server listening on port 10025
```

**Comment by jwulf** [comment]
Found it: I was missing 

```
var thisAdapter = require ("../../lib/SwarmCore.js").createAdapter("AtmaMailAdapter");
```

in my adapter code.
